### ISSUE TITLE
API Keys are deprecated and should be replaced with Personal Access Tokens

### ISSUE THREAD

**Issue by blissd** [libdns/gandi#10]
Gandi has deprecated API keys and replaced them with Personal Access Tokens, which are more secure because they have scoped permissions and expire after a user configurable period of time (max one year).

https://api.gandi.net/docs/authentication/

The deprecated API keys use an `Apikey` authorization scheme:
```
Authorization: Apikey 0123456
```

The new Personal Access Tokens use the `Bearer` authorization scheme:
```
Authorization: Bearer abc123
```
The Gandi provider for `libdns` should support Personal Access Tokens in addition to API Keys.

**Comment by chosroes** [comment]
Same problem

**Comment by obynio** [comment]
Fixed

**Comment by rringler** [comment]
Just curious; was this fixed elsewhere? It looks like #11 was closed unmerged?

**Comment by rringler** [comment]
Ah, n/m; looks like it was fixed in 5a260222d1a95412b414346cbccec30c885a55cc.
