### ISSUE TITLE
Relative/absolute record name conversions

### ISSUE THREAD

**Issue by mholt** [libdns/gandi#5]
Hi,

Over in the libdns repo, we're discussing standardizing the use of relative or absolute record names in `libdns.Record` structs. The current consensus is that they should be made relative (i.e. for a record named `sub.example.com` in a zone called `example.com`, the name should become `sub`). This may affect your provider implementation.

When you have a chance, would you please check out [this issue](https://github.com/libdns/libdns/issues/12#issuecomment-756135908)? This is the last call for feedback before we decide and I push the changes.

Link: https://github.com/libdns/libdns/issues/12#issuecomment-756135908

Thank you!

**Comment by matthiasng** [comment]
Hey @mholt, sry for the late response.

> If FQDN is `example.com` and zone is also `example.com` (either with or without trailing dot), should we return `""` or `"@"`?

[DOMAIN NAMES - rfc1035](https://tools.ietf.org/html/rfc1035) states the following: _A free standing @ is used to denote the current origin._
I think in both cases, some providers needs to implement special handling, but i feel an "at" is more convenient for the user. What do you mean ? 

> 2. If FQDN is `example.com` but zone is `example.net` (i.e. assuming zones are always suffixes of the FQDN, the FQDN cannot possibly be in the zone in this case), should we return `"example.com"` (i.e. return the input)?

Consider the following:
```
p.AppendRecords(context.TODO(), "exampe.com", []libdns.Record{
    {
        Type:  "TXT",
        Name:  libdns.RelativeName("example.com", "exampe.net"),
        Value: "test",
        TTL:   123,
    },
})
```
This would lead to `Record.Name == "example.com"` which violates the "relative names only" rule and depending on the provider, we need special handling for this.
I would rather shift this problem to the caller, by having 'RelativeName' return an error.

> 3. Are zones always suffixes of the FQDN?

_A zone is part of the domain namespace and is associated with a particular named domain_ - https://www.sciencedirect.com/topics/computer-science/domain-namespace
So my conclusion is: yes. :-D

> FWIW, Cloudflare's DNS API seems to accept both relative and absolute record names, equivalently. In my testing, using `sub.example.com` as the record name in a zone for `example.com`, and `sub` as the record name in the same zone of `example.com` both yielded the same results. When it returns the newly created records, its name always is absolute, even if the input was relative. It seems Cloudflare standardizes on full domain names. Why? Is that good practice? Should we be doing that instead?

So this means no need for a `RelativeName` function and the providers has to handle both cases and always return an absolute name. A'm i right ?

**Comment by obynio** [comment]
Hello there, sorry for the late reply. I've been a bit busy. I'll try to take a look at this asap :)

**Comment by mholt** [comment]
(Sorry, forgot about this issue!)

After much discussion we settled on using relative names with conversion functions to help: https://pkg.go.dev/github.com/libdns/libdns#AbsoluteName

Thanks for maintaining your libdns repo!
