### ISSUE TITLE
Request: allow overriding the API URL

### ISSUE THREAD

**Issue by voltagex** [libdns/gandi#7]
Would you consider allowing overriding the URL in https://github.com/libdns/gandi/blob/master/client.go#L146 (say, via an environment variable?)

I am probably overthinking this, but I am no longer comfortable with having a god-level API key to do a single call to Gandi, so I will probably write an API proxy. Gandi have stated they don't intend to allow granular access or multiple keys outside of Organisations (because what I'd really like is a key that can *only* update the record needed for the DNS challenge)

Couldn't see a better place to put this, so sorry if this isn't appropriate for a GitHub Issue.

**Comment by obynio** [comment]
We now have Personal Access Token that solves that issue
