### ISSUE TITLE
go.sum checksum mismatch

### ISSUE THREAD

**Issue by Xumeiquer** [libdns/gandi#9]
Hi, I am working on a project that uses this Go package and I am facing the following issue with Go modules.

```
verifying github.com/libdns/gandi@v1.0.2/go.mod: checksum mismatch
	downloaded: h1:VN+Lh8Teq6nYszNsPSLKdIv24hOCcQu0rJWHQa2jPZc=
	go.sum:     h1:hxpbQKcQFgQrTS5lV4tAgn6QoL6HcCnoBJaW5nOW4Sk=
```

Is there something to be fixed here?

Thanks.

**Comment by daniel-widrick** [comment]
I'm experiencing this same issue trying to install on fedora.

**Comment by thatcher-gaming** [comment]
same thing here.. not sure what's going on

**Comment by obynio** [comment]
Fixed
